import type {NextPage} from "next";
import React, {useMemo, useState} from "react";
import Head from "next/head";
import raw_data from "public/data/usa-delta-prevalence.csv";
import _ from "lodash";
import {Box, Flex, Text} from "@chakra-ui/react";
import {ChoroplethMap, Header, Timeline} from "src/components";
import {processRawData} from "src/helpers/data";
import {StyledSection} from "src/components/Header/styles";

const Home: NextPage = () => {
  // Represents the position in the data that is currently on display.
  const [currentIndex, setCurrentIndex] = useState(0);

  // Shape raw data.
  const {data} = useMemo(() => processRawData(raw_data), []);

  return (
    <div>
      <Head>
        <title>Delta Prevalence in USA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box>
          <Header />
          <Flex m={4} justifyContent={"center"}>
            <Box width={"100%"}>
              <ChoroplethMap data={data} currentIndex={currentIndex} />
              <StyledSection pt={[4, 10]}>
                <Timeline
                  label={data[currentIndex].date}
                  min={0}
                  max={data.length - 1}
                  defaultValue={currentIndex}
                  setCurrentIndex={setCurrentIndex}
                />
                <Text textStyle={"body"} fontSize={"xs"} mt={2}>
                  Source: Population data retrieved from 2020 census, U.S.
                  Census Bureau.
                  <br />
                  Source: State mask mandate data retrieved from Ballotpedia.
                </Text>
              </StyledSection>
            </Box>
          </Flex>
        </Box>
      </main>
    </div>
  );
};

export default Home;
