import type {NextPage} from "next";
import {useState} from "react";
import Head from "next/head";
import * as d3 from "d3";
import raw_data from "public/data/usa-delta-prevalence.csv";
import {Box} from "@chakra-ui/react";
import _ from "lodash";
import {ChoroplethMap, Header, PageLayout, Timeline} from "src/components";
import {LocationDataProps, get_processed_data} from "src/helpers/data";

interface DataProps {
  date: string;
  entries: LocationDataProps[];
}

const Home: NextPage = () => {
  // Represents the position in the data that is currently on display.
  const [currentIndex, setCurrentIndex] = useState(0);

  const data = get_processed_data(raw_data).sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime(),
  );

  return (
    <div>
      <Head>
        <title>Delta Prevalence in USA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PageLayout>
          <Header />
          <Box m={4}>
            <ChoroplethMap />
            <Timeline
              label={data[currentIndex].date}
              min={0}
              max={data.length - 1}
              defaultValue={currentIndex}
              setCurrentIndex={setCurrentIndex}
            />
          </Box>
        </PageLayout>
      </main>
    </div>
  );
};

export default Home;
